version: "3.9"

name: url-shortener_prod

services:
  server:
    container_name: "url-shortener_server_prod"
    restart: always
    build: server
    command: npm run start:prod
    expose:
      - 5000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /app/node_modules
  nginx:
    image: nginx
    restart: "no"
    container_name: "url-shortener_nginx_prod"
    ports:
      - ${DOCKER_PORT:-80}:80
    depends_on:
      - server
    volumes:
      - ./client/dist/spa:/usr/share/nginx/html
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/prod:/etc/nginx/conf.d
