version: "3.9"

name: url-shortener_dev

services:
  server:
    container_name: "url-shortener_server_dev"
    restart: always
    build: server
    command: npm run start:prod
    expose:
      - 5000
    depends_on:
      - db
    env_file:
      - ./dev.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /app/node_modules
  nginx:
    image: nginx
    restart: "no"
    container_name: "url-shortener_nginx_dev"
    # ports:
      # - 4003:80
    # uncomment this if you want to use nginx in dev mode
    ports:
      - 80:80
      - 443:443
    depends_on:
      - server
    volumes:
      - ./client/dist/spa:/usr/share/nginx/html
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/dev:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  
  db:
    container_name: url-shortener_db_dev
    image: postgres:15
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_DB=$DB_DATABASE
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/dev:/var/lib/postgresql/data/pgdata
  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
